// react_front/src/components/ChatInput.js
import React, { useState, useRef } from "react";
import request from "../utils/request";
import SendIcon from "@mui/icons-material/Send";
import CancelScheduleSendIcon from '@mui/icons-material/CancelScheduleSend';
import {
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Button,
  CircularProgress,
  Box,
} from "@mui/material";

const ChatInput = ({ projects, addMessage }) => {
  const [userInput, setUserInput] = useState("");
  const [selectedProject, setSelectedProject] = useState("");
  const [selectedMode, setSelectedMode] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [timer, setTimer] = useState(0);
  const timerRef = useRef(0);
  const intervalId = useRef(null);

  const handleSend = async () => {
    if (selectedProject && (selectedMode === "Question Extraction" || userInput.trim())) {
      const formData = new FormData();
      formData.append("project_name", selectedProject);
  
      if (selectedMode !== "Question Extraction") {
        formData.append("query", userInput);
      }
  
      if (selectedMode === "Question Extraction") {
        addMessage({ sender: "user", text: "Question Extraction\n(" + selectedProject + ")" });
      } else {
        addMessage({ sender: "user", text: userInput + "\n(" + selectedProject + ")" });
      }
  
      setUserInput("");
      setIsLoading(true);
      startTimer();
  
      let apiPath;
      switch (selectedMode) {
        case "Question Extraction":
          apiPath = "/get_question/";
          break;
        case "Simple Answer":
          apiPath = "/get_simple_answer_verbose/";
          break;
        case "Detailed Answer":
          apiPath = "/get_detailed_answer_verbose/";
          break;
        default:
          console.warn("Invalid mode selected");
          return;
      }
  
      try {
        const response = await request.post(apiPath, formData);
        stopTimer();
        const finalTime = timerRef.current;
  
        let answer;
        if (selectedMode === "Question Extraction") {
          answer = 
            response.answer +
              "\n\n <strong>Total Response Time:</strong> " +
              finalTime +
              " seconds";
        } else {
          answer =
            response.answer.answer +
            "\n\n <strong>Total Response Time:</strong> " +
            finalTime +
            " seconds";
        }
  
        const rfp_local_context = response.answer.rfp_local_context;
        const company_local_context = response.answer.company_local_context;
        const rfp_general_context = response.answer.rfp_general_context;
        const company_general_context = response.answer.company_general_context;
  
        addMessage({
          sender: "bot",
          project_name: selectedProject,
          query: userInput,
          text: answer,
          rfp_local_context: rfp_local_context,
          company_local_context: company_local_context,
          rfp_general_context: rfp_general_context,
          company_general_context,
        });
      } catch (error) {
        console.error("Error fetching answer:", error);
        addMessage({ sender: "bot", text: "Error retrieving answer. Please try again later." });
      } finally {
        setIsLoading(false);
      }
    }
  };
  

  const startTimer = () => {
    setTimer(0);
    timerRef.current = 0;
    intervalId.current = setInterval(() => {
      setTimer((prevTimer) => {
        timerRef.current = prevTimer + 1;
        return prevTimer + 1;
      });
    }, 1000);
  };

  const stopTimer = () => {
    clearInterval(intervalId.current);
    intervalId.current = null;
  };

  return (
    <Box
      sx={{
        p: 2,
        display: "flex",
        flexDirection: "column",
        gap: 2,
        backgroundColor: "#3A3A3A",
        borderRadius: "5px", // Rounded borders
        borderTop: "1px solid #dddddd", // Top separator line
        fontFamily: "'Roboto', sans-serif", // Apply the Roboto font globally to the component
      }}
    >
      {/* Dropdowns and Loading */}
      <Box
        sx={{
          display: "flex",
          gap: 2,
          alignItems: "center",
        }}
      >
        {/* Project Selector */}
        <FormControl sx={{ minWidth: 200 }}>
          <InputLabel
            id="project-select-label"
            sx={{
              color: "#F5F5F5", // White font
              fontSize: "0.9rem", // Adjust font size
              fontFamily: "'Roboto', sans-serif", // Apply Roboto font
            }}
          >
            Select a project
          </InputLabel>
          <Select
            labelId="project-select-label"
            value={selectedProject}
            onChange={(e) => setSelectedProject(e.target.value)}
            label="Choose Project"
            sx={{
              backgroundColor: "#4A4A4A", // Dark gray background
              color: "#F5F5F5", // White font
              fontSize: "0.9rem", // Adjust font size
              fontFamily: "'Roboto', sans-serif", // Apply Roboto font
            }}
          >
            <MenuItem value="" disabled>
              Project
            </MenuItem>
            {projects.map((project, index) => (
              <MenuItem
                key={index}
                value={project.name}
                sx={{ fontFamily: "'Roboto', sans-serif" }} // Apply Roboto font to dropdown items
              >
                {project.name}
              </MenuItem>
            ))}
          </Select>
        </FormControl>

        {/* Mode Selector */}
        <FormControl sx={{ minWidth: 200 }}>
          <InputLabel
            id="mode-select-label"
            sx={{
              color: "#F5F5F5", // White font
              fontSize: "0.9rem", // Adjust font size
              fontFamily: "'Roboto', sans-serif", // Apply Roboto font
            }}
          >
            Select a mode
          </InputLabel>
          <Select
            labelId="mode-select-label"
            value={selectedMode}
            onChange={(e) => setSelectedMode(e.target.value)}
            label="Mode"
            sx={{
              backgroundColor: "#4A4A4A", // Dark gray background
              color: "#F5F5F5", // White font
              fontSize: "0.9rem", // Adjust font size
              fontFamily: "'Roboto', sans-serif", // Apply Roboto font
            }}
          >
            <MenuItem value="" disabled>
              Mode
            </MenuItem>
            <MenuItem value="Question Extraction">Question Extraction (0 to 5 min)</MenuItem>
            <MenuItem value="Simple Answer">Simple Answer (3 to 10 min)</MenuItem>
            <MenuItem value="Detailed Answer">Detailed Answer (5 to 20 min)</MenuItem>
          </Select>
        </FormControl>

        {/* Loading Indicator */}
        {isLoading && (
          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              gap: 1,
              color: "#F5F5F5", // White font
              minWidth: 100, // Reserve space for loading icon and text
              fontFamily: "'Roboto', sans-serif", // Apply Roboto font
            }}
          >
            <CircularProgress size={20} />
            <span>{timer}s</span>
          </Box>
        )}
      </Box>

      {/* Input Field */}
      <Box sx={{ display: "flex", gap: 2, alignItems: "center" }}>
        <TextField
          fullWidth
          placeholder="Please enter a query..."
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
          onKeyUp={(e) => e.key === "Enter" && handleSend()}
          variant="outlined"
          sx={{
            backgroundColor: "#4A4A4A", // Dark gray background
            color: "#F5F5F5", // White font
            borderRadius: "5px", // Rounded borders
            fontFamily: "'Roboto', sans-serif", // Apply Roboto font
          }}
          InputProps={{
            style: { color: "#F5F5F5", fontFamily: "'Roboto', sans-serif" }, // White input text and Roboto font
          }}
        />
        <Button
          onClick={handleSend}
          variant="contained"
          sx={{
            backgroundColor: isLoading || !selectedMode || !selectedProject ? "#1A1A1A" : "#5A5A5A", // Change background color based on disabled state
            color: "#F5F5F5", // Icon color remains white
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            "&:hover": {
              backgroundColor: isLoading || !selectedMode || !selectedProject ? "#1A1A1A" : "#7A7A7A", // Keep hover effect for enabled state
            },
            borderRadius: "5px",
            width: "50px", // Adjust width
            height: "50px", // Adjust height
            fontFamily: "'Roboto', sans-serif", // Apply Roboto font to the button
          }}
          disabled={isLoading || !selectedMode || !selectedProject}
        >
          {isLoading || !selectedMode || !selectedProject ? (
            <CancelScheduleSendIcon sx={{ color: "#E0E0E0" }} />
          ) : (
            <SendIcon />
          )}
        </Button>
      </Box>
    </Box>
  );
};

export default ChatInput;

// legacy/vue_front/src/components/ChatInput.vue
<template>
  <div class="chat-input">
    <!-- Project Selector -->
    <div class="project-selector">
      <label for="project-select">Choose Project:</label>
      <div class="select-with-loading">
        <select id="project-select" v-model="selectedProject">
          <option v-for="project in projects" :key="project.id" :value="project.name">
            {{ project.name }}
          </option>
        </select>
        <label for="mode-select" style="margin-left: 10px;">Mode:</label>
        <select id="mode-select" v-model="selectedMode">
          <option value="Question Extraction">Question Extraction</option>
          <option value="Simple Answer Verbose">Simple Answer Verbose</option>
          <option value="Detailed Answer Verbose">Detailed Answer Verbose</option>
          <option value="Simple Answer">Simple Answer</option>
          <option value="Detailed Answer">Detailed Answer</option>
        </select>
        <!-- Loading Icon and Timer -->
        <div class="loading-with-timer" v-if="isLoading">
          <el-icon class="loading-icon">
            <Loading />
          </el-icon>
          <span>{{ timer }}s</span> <!-- Timer Display -->
        </div>
      </div>
    </div>

    <!-- Input and Send Button -->
    <div class="input-container">
      <input v-model="userInput" type="text" placeholder="Please enter a query..." @keyup.enter="sendMessage" />
      <button @click="sendMessage">Send</button>
    </div>
  </div>
</template>

<script>
import { Loading } from '@element-plus/icons-vue';

export default {
  components: {
    Loading
  },
  props: {
    projects: {
      type: Array,
      required: true
    }
  },
  data() {
    return {
      userInput: '',
      selectedProject: '', // 选择的项目名称
      selectedMode: '',
      isLoading: false, // 控制 Loading 图标显示
      timer: 0, // 用于计时器的变量
      intervalId: null // 用于存储计时器的ID
    };
  },
  methods: {
    async sendMessage() {
      if (this.selectedProject && (this.selectedMode === 'Question Extraction' || this.userInput.trim())) {
        this.$emit('add-message', { sender: 'user', text: this.userInput });

        // 创建 FormData 对象
        const formData = new FormData();
        formData.append("project_name", this.selectedProject);

        // Only append query if the mode is not "Question Extraction"
        if (this.selectedMode !== 'Question Extraction') {
          formData.append("query", this.userInput);
        }

        if (this.selectedMode === 'Question Extraction') {
          this.$emit('add-message', { sender: 'user', text: "Question Extraction" });
        }
        
        // 清空输入框
        this.userInput = ''; 

        // 设置 isLoading 为 true 显示 Loading 图标
        this.isLoading = true;
        this.startTimer(); // 开始计时

        // 根据 selectedMode 选择不同的 API 路径
        let apiPath;
        switch (this.selectedMode) {
          case 'Question Extraction':
            apiPath = '/get_question/';
            break;
          case 'Simple Answer Verbose':
            apiPath = '/get_simple_answer_verbose/';
            break;
          case 'Detailed Answer Verbose':
            apiPath = '/get_detailed_answer_verbose/';
            break;
          case 'Simple Answer':
            apiPath = '/get_simple_answer/';
            break;
          case 'Detailed Answer':
            apiPath = '/get_detailed_answer/';
            break;
          default:
            console.warn('Invalid mode selected');
            return;
        }

        try {
          const response = await this.$request.post(apiPath, formData, {
            headers: {
              'Content-Type': 'multipart/form-data'
            }
          });
          const answer = response.answer + "\n\n <strong>Total Response Time:</strong> " + this.timer + " seconds"
          this.$emit('add-message', { sender: 'bot', text: answer });
        } catch (error) {
          console.error('Error fetching answer:', error);
          this.$emit('add-message', { sender: 'bot', text: 'Error retrieving answer. Please try again later.' });
        } finally {
          // 请求结束后隐藏 Loading 图标
          this.isLoading = false;
          this.stopTimer(); // 停止计时
        }
      }
    },
    startTimer() {
      this.timer = 0;
      this.intervalId = setInterval(() => {
        this.timer += 1;
      }, 1000);
    },
    stopTimer() {
      clearInterval(this.intervalId);
      this.intervalId = null;
      this.timer = 0; // 重置计时器
    }
  }
};
</script>

<style scoped>
.loading-with-timer {
  display: flex;
  align-items: center;
}

.loading-with-timer .loading-icon {
  margin-right: 5px;
}
</style>


<style scoped>
.select-with-loading {
  display: flex;
  align-items: center;
}

.loading-icon {
  animation: rotating 2s linear infinite;
  margin-left: 8px;
}

.chat-input {
  display: flex;
  flex-direction: column;
  padding: 10px;
}
.project-selector {
  display: flex;
  align-items: center;
  margin-bottom: 10px;
}
.project-selector label {
  margin-right: 10px;
}
.project-selector select {
  padding: 5px;
  border-radius: 5px;
  border: 1px solid #ddd;
}
.input-container {
  display: flex;
  align-items: center;
}
.input-container input {
  flex: 1;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 5px;
  margin-right: 10px;
}
.input-container button {
  padding: 10px 15px;
  background-color: #2196f3;
  color: white;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}
</style>
